import { StyleSheet,Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFFFFF",
    },
    header: {
        height: 60,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#EEEEEE",
    },
    headerLogo: {
        width: 100,
        height: 40,
    },
    notificationButton: {
        position: "relative",
        padding: 5,
    },
    notificationBadge: {
        position: "absolute",
        top: 0,
        right: 0,
        backgroundColor: "#FF0000",
        width: 16,
        height: 16,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
    },
    notificationBadgeText: {
        color: "#FFFFFF",
        fontSize: 10,
        fontWeight: "bold",
    },
    content: {
        flex: 1,
        padding: 16,
    },
    welcomeSection: {
        marginTop: 10,
        marginBottom: 20,
    },
    welcomeText: {
        color: "#000000",
        fontSize: 22,
        fontWeight: "bold",
    },
    usernameText: {
        color: "#000000",
    },
    subText: {
        color: "#777777",
        fontSize: 16,
        marginTop: 5,
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 24,
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#000",
    },
    liveMatchCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        overflow: "hidden",
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#E0E0E0",
        padding: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    liveMatchHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    liveIndicatorContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 0, 0, 0.1)",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    liveDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#FF0000",
        marginRight: 5,
    },
    liveText: {
        color: "#FF0000",
        fontSize: 12,
        fontWeight: "bold",
    },
    tournamentContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    tournamentLogo: {
        width: 20,
        height: 20,
        marginRight: 5,
    },
    tournamentName: {
        fontSize: 12,
        color: "#777777",
    },
    teamsContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
    },
    teamSection: {
        alignItems: "center",
        width: "40%",
    },
    teamLogo: {
        width: 60,
        height: 60,
        marginBottom: 8,
    },
    teamName: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#000000",
    },
    scoreContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        width: "20%",
    },
    scoreText: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#000000",
        paddingHorizontal: 5,
    },
    scoreDivider: {
        fontSize: 24,
        color: "#777777",
    },
    watchButtonContainer: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
    },
    watchButton: {
        backgroundColor: "#FF0000",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
    },
    watchButtonWatchParty: {
        backgroundColor: "#6441a5",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
    },
    watchButtonText: {
        color: "#FFFFFF",
        fontWeight: "bold",
        fontSize: 14,
        marginLeft: 5,
    },
    mainCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        overflow: "hidden",
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#E0E0E0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    mainCardImage: {
        width: "100%",
        height: 250,
        resizeMode: "cover",
    },
    mainCardContent: {
        padding: 16,
    },
    mainCardTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#000000",
        marginBottom: 8,
    },
    mainCardDescription: {
        fontSize: 14,
        color: "#555555",
        lineHeight: 20,
    },
    tabsContainer: {
        marginTop: 10,
        marginBottom: 20,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#EEEEEE",
        overflow: "hidden",
    },
    tabsHeader: {
        flexDirection: "row",
        borderBottomWidth: 1,
        borderBottomColor: "#EEEEEE",
    },
    tab: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 5,
    },
    activeTab: {
        borderBottomWidth: 2,
        borderBottomColor: "#000000",
    },
    tabText: {
        fontSize: 12,
        color: "#777777",
        marginLeft: 5,
    },
    activeTabText: {
        color: "#000000",
        fontWeight: "bold",
    },
    tabContent: {
        padding: 16,
    },
    gameCard: {
        flexDirection: "row",
        backgroundColor: "#F9F9F9",
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
        alignItems: "center",
    },
    gameImage: {
        width: 80,
        height: 50,
        borderRadius: 6,
        marginRight: 12,
    },
    gameInfo: {
        flex: 1,
    },
    gameTitle: {
        fontSize: 16,
        fontWeight: "bold",
        marginBottom: 4,
        color: "#000000",
    },
    upcomingMatch: {
        fontSize: 12,
        color: "#0000000",
        marginBottom: 4,
    },
    lastResult: {
        fontSize: 12,
        color: "#777777",
    },
    streamerCard: {
        flexDirection: "row",
        backgroundColor: "#F9F9F9",
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
        alignItems: "center",
    },
    streamerImage: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginRight: 12,
    },
    streamerInfo: {
        flex: 1,
    },
    streamerHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 4,
    },
    streamerName: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#000000",
        marginRight: 8,
    },
    liveIndicator: {
        backgroundColor: "rgba(255, 0, 0, 0.1)",
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    streamerGame: {
        fontSize: 12,
        color: "#555555",
        marginBottom: 2,
    },
    streamerViewers: {
        fontSize: 12,
        color: "#9E9EB3",
    },
    streamerAvatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginRight: 15,
    },
    viewerCount: {
        fontSize: 12,
        color: "#777777",
    },
    fcCard: {
        flexDirection: "row",
        backgroundColor: "#F9F9F9",
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
        alignItems: "center",
    },
    fcImage: {
        width: 80,
        height: 90,
        borderRadius: 6,
        marginRight: 12,
    },
    fcInfo: {
        flex: 1,
    },
    fcTitle: {
        fontSize: 14,
        color: "#777777",
        marginBottom: 4,
    },
    fcMatch: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#000000",
        marginBottom: 4,
    },
    fcNextMatch: {
        fontSize: 12,
        color: "#000000",
    },
    exploreMoreButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 10,
    },
    exploreMoreText: {
        fontSize: 14,
        color: "#0000000",
        fontWeight: "600",
        marginRight: 5,
    },
    tweetCarouselContainer: {
        paddingRight: 16,
    },
    tweetCard: {
        width: width - 80,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        padding: 16,
        marginRight: 12,
        borderWidth: 1,
        borderColor: "#EEEEEE",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    tweetHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    tweetAvatar: {
        width: 30,
        height: 30,
        borderRadius: 15,
        marginRight: 8,
    },
    tweetName: {
        fontWeight: "bold",
        fontSize: 14,
        color: "#000000",
    },
    tweetHandle: {
        fontSize: 12,
        color: "#777777",
    },
    twitterIcon: {
        marginLeft: "auto",
    },
    tweetText: {
        fontSize: 14,
        color: "#333333",
        lineHeight: 20,
        marginBottom: 12,
    },
    tweetDate: {
        fontSize: 12,
        color: "#777777",
    },
    loadingContainer: {
        alignItems: "center",
        justifyContent: "center",
        height: 100,
    },
    loadingText: {
        fontSize: 14,
        color: "#777777",
    },
    engagementContainer: {
        margin: 20,
        alignItems: "center",
    },
    engagementlabel: {
        fontSize: 18,
        marginBottom: 10,
        fontWeight: "bold",
    },
    barBackground: {
        width: "100%",
        height: 20,
        backgroundColor: "#e0e0e0",
        borderRadius: 10,
        overflow: "hidden",
    },
    barFill: {
        height: "100%",
        backgroundColor: "#ef4444", // vermelho forte
        borderRadius: 10,
    },
    percentage: {
        marginTop: 5,
        fontSize: 16,
        fontWeight: "600",
    },
    fansRankingContainer: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#EEEEEE",
    },
    userRankingContainer: {
        marginBottom: 16,
    },
    yourRankingCard: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#F0F0F0",
        borderRadius: 8,
        padding: 12,
    },
    yourRankingInfo: {
        flexDirection: "row",
        alignItems: "center",
    },
    userAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        marginRight: 10,
    },
    yourRankingText: {
        fontSize: 12,
        color: "#777777",
    },
    yourRankingPosition: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#000000",
    },
    yourPointsContainer: {
        alignItems: "center",
    },
    yourPoints: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#FF0000",
    },
    pointsLabel: {
        fontSize: 12,
        color: "#777777",
    },
    fanRankingRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#EEEEEE",
    },
    fanRanking: {
        width: 24,
        fontSize: 16,
        fontWeight: "bold",
        color: "#777777",
    },
    fanAvatar: {
        width: 30,
        height: 30,
        borderRadius: 15,
        marginRight: 10,
    },
    fanName: {
        flex: 1,
        fontSize: 14,
        color: "#000000",
    },
    fanPoints: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#FF0000",
    },
    viewFullRankingButton: {
        alignItems: "center",
        marginTop: 16,
        paddingVertical: 8,
    },
    viewFullRankingText: {
        fontSize: 14,
        color: "#777777",
    },
    promoCarouselContainer: {
        paddingRight: 16,
    },
    promoCard: {
        width: width - 60,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        overflow: "hidden",
        marginRight: 12,
        borderWidth: 1,
        borderColor: "#EEEEEE",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    promoImage: {
        width: "100%",
        height: 250,
        resizeMode: "cover",
    },
    promoContent: {
        padding: 16,
    },
    promoTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#000000",
        marginBottom: 8,
    },
    promoDescription: {
        fontSize: 14,
        color: "#555555",
        marginBottom: 16,
    },
    promoButton: {
        backgroundColor: "#000000",
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 16,
        alignItems: "center",
        alignSelf: "flex-start",
    },
    promoButtonText: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "bold",
    },
    countdownContainer: {
        borderRadius: 12,
        padding: 16,
        marginTop: 24,
        alignItems: "center",
        overflow: "hidden",
        position: "relative",
        height: 150,
        width: "100%",
    },
    countdownBackground: {
        ...StyleSheet.absoluteFillObject, 
        width: undefined, 
        height: undefined, 
        resizeMode: "cover",
    },
    countdownOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    countdownTitle: {
        color: "#FFFFFF",
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 8,
        zIndex: 1,
    },
    countdownRow: {
        flexDirection: "row",
        alignItems: "center",
        zIndex: 1,
    },
    countdownText: {
        color: "#FFFFFF",
        fontSize: 14,
        marginRight: 5,
    },
    countdownDays: {
        color: "#FF0000",
        fontSize: 18,
        fontWeight: "bold",
    },
    furiaBot: {
        position: "absolute",
        right: 16,
        bottom: 80,
        backgroundColor: "#000000",
        borderRadius: 20,
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 8,
        paddingHorizontal: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    furiaBotText: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "bold",
        marginLeft: 5,
    },
    bottomNav: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        height: 70,
        backgroundColor: "#F7F7F7",
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        borderTopWidth: 1,
        borderTopColor: "#E0E0E0",
        paddingBottom: 10,
    },
    navItem: {
        alignItems: "center",
        justifyContent: "center",
    },
    navText: {
        fontSize: 12,
        marginTop: 4,
        color: "#000000",
        fontWeight: "bold",
    },
    navTextInactive: {
        fontSize: 12,
        marginTop: 4,
        color: "#777777",
    },
});
