services:
  - type: web
    name: furia-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_URL
        value: https://furia-api.onrender.com
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:TF5Ea1ElXO3crTD+y5OIF/5dzJXqaJbZstpNrCRHMMU=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: furia-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: furia-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: furia-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: furia-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: furia-db
          property: password
      - key: TWITTER_BEARER_TOKEN
        value: AAAAAAAAAAAAAAAAAAAAAEt%2B0wEAAAAAgK9GHgQqWXSZ1aTisxVXy9DXS0A%3DLzU6giTkEfHmn7LIKRYqJDVbfoXqkgVfnsePiBkDQX35EPUChW
      - key: TWITCH_ACCESS_TOKEN
        value: yviiw7dqrlrl9044ehnfzm3ak1x0di
      - key: TWITCH_CLIENT_ID
        value: 7b3xuvlzmrxhui1bcztth7tbves6gh

  - type: postgres
    name: furia-db
    plan: free
    region: oregon
    ipAllowList: []

startCommand: /usr/local/bin/docker-entrypoint.sh
